### ISSUE TITLE
Bug with 1.7.10 5zig

### ISSUE THREAD

**Issue by ridalarry** [Gerrygames/ClientViaVersion#1]
when I try to use 1.8 or above I get this error
https://gyazo.com/26e00838c93b87e8f8ac5e00f1ee1e46

**Comment by Gerrygames** [comment]
Could you send me your client log? (Please make sure to remove your session id from it!)

**Comment by ridalarry** [comment]
Client side
https://pastebin.com/NvbD3NBP

Server side
https://pastebin.com/77xAHkLq

I don't know but it seems like there is no error in the logs related unless it is this one "Could not add buttons to gui."

Also its weird the error seems to be trying to translate 1.9 chunks to 1.8 while the server is already 1.8.8

**Comment by Gerrygames** [comment]
Please try the new version I uploaded yesterday. I think I know what the issue was.

**Comment by ridalarry** [comment]
It got fixed, but for some reason I can't stand on carpets

UPDATE: This was caused by the anti hacks
