### ISSUE TITLE
Kicked error

### ISSUE THREAD

**Issue by Michael1297** [Gerrygames/ClientViaVersion#2]
I get this error on join 
client: 1.8.9
server: 1.12.2
client log: https://paste.ee/p/RRuGr
![2018-05-10_11 17 21](https://user-images.githubusercontent.com/38764610/39857269-61959b76-543b-11e8-8528-39df205e81e4.png)

**Comment by Gerrygames** [comment]
This is an issue in ViaBackwards. It isn't handling the fallingblock particles correctly. I will open an issue for it.

//Edit: There is already an issue for this: https://github.com/Matsv/ViaBackwards/issues/44
