### ISSUE TITLE
Why is this repository still not archived?

### ISSUE THREAD

**Issue by ghost** [Gerrygames/ClientViaVersion#8]
I'm asking this because you said this project is discontinued.

**Comment by florianreuth** [comment]
Why should it?

**Comment by ghost** [comment]
lmao

**Comment by florianreuth** [comment]
Simply do not open unnecessary issues that offer no added value ¯\_(ツ)_/¯

**Comment by ghost** [comment]
sure florian michael
![florian](https://user-images.githubusercontent.com/58796076/150685032-9a66e242-c008-4af6-9270-bbdd9a09ed15.png)
l

**Comment by FooFieOwO** [comment]
<img src="https://c.tenor.com/mm6gNAyiobUAAAAC/emotional-damage.gif">

**Comment by EcstasyCode** [comment]
![loli-dance-4](https://user-images.githubusercontent.com/67347965/150685131-d6a2752e-86d3-4878-90fd-b24d7528d708.gif)

**Comment by ghost** [comment]
ya so wie die github repo mit seinen clients

**Comment by EcstasyCode** [comment]
![loli-dance-5](https://user-images.githubusercontent.com/67347965/150685135-679c7f8a-94b8-4f31-ad22-28c1a90a1a3e.gif)

**Comment by florianreuth** [comment]
cringe kids
